### ISSUE TITLE
Podcast post meta still remains after deleting the podcast block

### ISSUE THREAD

**Issue by dinhtungdu** [10up/simple-podcasting#88]
**Describe the bug**

After deleting the podcast block, the podcast meta still remains in the post meta table.
**Steps to Reproduce**

1. Create a new podcast and an episode for that podcast.
2. Edit the episode, delete the podcast block, and save changes.
3. See the podcast meta still remains in the meta table.

**Expected behavior**

The podcast meta should be cleared after deleting the podcast block.

Relate #86

**Comment by helen** [comment]
This was originally fixed in #52, can we investigate and see what happened that this is happening again?

**Comment by dinhtungdu** [comment]
@helen I can still reproduce this issue with the latest commit on `develop`.

**Comment by dinhtungdu** [comment]
@helen, in #52, we partially fixed the post meta deletion issue: [`66a4268` (#52)](https://github.com/10up/simple-podcasting/pull/52/commits/66a42683f91e0ffda61182af0a2d8052b8d8fe9c). I say 'paritally' because there are two metas left: `podcast_explicit` and `podcast_captioned`.

The approach we use also introduces a minor issue: When a podcast block is deleted, we get this warning in the console log. This issue breaks transformation introduces in #85 as detailed below.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

#85 introduces the block transformation and the code that deletes post meta was removed: [`99a5fb0` (#85)](https://github.com/10up/simple-podcasting/pull/85/commits/99a5fb0c9cfa9e824963ea4fd53e63a45234693c).
